name: Deploy 1000h website

on:
  push:
    branches:
      - main
    path:
      - "1000-hours/**"
  pull_request:
    branches:
      - main
    path:
      - "1000-hours/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      # checkout the code
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            1000-hours/node_modules
            1000-hours/**/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./1000-hours/package-lock.json') }}

      - name: Setup node env
        uses: actions/setup-node@master
        with:
          node-version: "20"

      - run: npm install
        working-directory: 1000-hours

      - run: npm run docs:build
        working-directory: 1000-hours

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .vitepress/dist --project-name=1000-hours-prod
          workingDirectory: "1000-hours"